sudo: required

language: node

services:
  - docker

before_install:
  - docker pull node
  - docker run -d node /bin/sh -c "node -v"
  - docker ps -a
  - npm -v
  - node -v

script:
  - npm -v
  - node -v

